language: go

sudo: false

go:
  - "1.10"
  - "1.11"
  - "1.13"
  - "1.14"
  - "1.15"
  - tip

before_install:
  - go get -t -v ./...

script:
  - sh coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
